global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-exporter'  
    static_configs:
      - targets: ['kafka-exporter:9308'] 
    metrics_path: '/metrics'

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: '/metrics/prometheus'

  - job_name: 'spark-workers'
    static_configs:
      - targets: ['spark-worker1:8081', 'spark-worker2:8081', 'spark-worker3:8081']
    metrics_path: '/metrics/prometheus'
  


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  

rule_files:
  - './rules.yml'  

