global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-exporter'  
    static_configs:
      - targets: ['kafka-exporter:9308'] 
    metrics_path: '/metrics'

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: '/metrics/prometheus'

  - job_name: 'spark-workers'
    static_configs:
      - targets: ['spark-worker3:8081']
    metrics_path: '/metrics/prometheus'
  

  # - job_name: 'spark-workers'
  #   static_configs:
  #     - targets: ['spark-worker1:8081', 'spark-worker2:8081', 'spark-worker3:8081']
  #   metrics_path: '/metrics/prometheus'


  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['kafka1:27071', 'kafka2:27072', 'kafka3:27073', 'kafka4:27074']
  # - job_name: 'kafka_exporter'
  #   static_configs:
  #     - targets: ['kafka-exporter:9308']
  # - job_name: 'spark_master'
  #   static_configs:
  #     - targets: ['spark-master:27075']
  # - job_name: 'spark_worker'
  #   static_configs:
  #     - targets: ['spark-worker3:27078']
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['prometheus:9090']
  


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  

rule_files:
  - './rules.yml'  

