# Confluent Schema Registry base image
FROM confluentinc/cp-schema-registry:7.4.0


# COPY kafka/schema-registry/schema-registry.properties /etc/schema-registry/schema-registry.properties


EXPOSE 8089
EXPOSE 9101

# Set environment variables 
ENV SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9093,kafka3:9094,kafka4:9095
ENV SCHEMA_REGISTRY_HOST_NAME=schema-registry
ENV SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8089
ENV SCHEMA_REGISTRY_AVRO_AUTO_REGISTER_SCHEMAS=true
ENV SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY=BACKWARD
# ENV KAFKA_JMX_PORT: 9101
# ENV JMX_PORT: 9101
# # have to download the file for now excluding it, will download later
# ENV KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=9101:/usr/share/jmx_exporter/schema-registry.yml"

COPY backend/kafka/schema-registry/entrypoint.sh /entrypoint.sh



ENTRYPOINT ["/entrypoint.sh"]
