services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - verdantiq_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - verdantiq_network

  test:
    build:
      context: .
      dockerfile: test-services/Dockerfile
    container_name: test-api
    # env_file:
    #   - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app/test-services 
    command: ["pytest", "-v", "tests"]
    environment:
      - PYTHONPATH=/app
    networks:
      - verdantiq_network

volumes:
  postgres_data:

networks:
  verdantiq_network:
    driver: bridge
