export const linkMap: Record<string, string> = {
  "/dashboard": "Dashboard",
  "/dashboard/recent-activities": "Dashboard",
  "/admin": "Admin Dahboard",
  "/admin/feedback": "Admin Feedback",
  "/profile": "Profile",
  "/payment": "Payment",
  "/questions": "Questions",
  "/questions/workarea": "Questions",
  "/demo": "Demo",
  "/demo/workarea": "Demo",
  "/settings": "Settings",
  "/settings/crypto": "Crypto",
  "/settings/claim-reward": "Crypto Reward",
  "/settings/security": "Security",
  "/settings/faqs": "FAQs",
  "/settings/feedback": "Feedback",
  "/settings/invite-friends": "Invite Friends",
  "/settings/change-password": "Change Password",
};
